-- App Top modèles / Réassort : tables top_modeles + reassorts (RLS off, temps réel on)
create table if not exists top_modeles (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  magasin_id bigint,
  fournisseur_id bigint,
  modele text,
  numero text,
  categorie text,
  type_key text,
  season text,
  pointures jsonb default '[]'::jsonb,
  stock jsonb default '{}'::jsonb,
  stock_at timestamptz,
  cible integer default 1,
  note text
);
create table if not exists reassorts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  top_id bigint,
  magasin_id bigint,
  fournisseur_id bigint,
  modele text,
  season text,
  statut text default 'À réassortir',
  sizes jsonb default '{}'::jsonb,
  recu jsonb default '{}'::jsonb,
  etapes jsonb default '{}'::jsonb,
  receptions jsonb default '[]'::jsonb,
  par text,
  note text
);
alter table top_modeles disable row level security;
alter table reassorts disable row level security;
do $$ begin
  begin alter publication supabase_realtime add table top_modeles; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table reassorts; exception when duplicate_object then null; end;
end $$;
-- Exposition à l'API (les nouveaux projets Supabase n'ouvrent plus les tables automatiquement)
grant all on table public.top_modeles, public.reassorts to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
notify pgrst, 'reload schema';
